_wandb:
    value:
        cli_version: 0.22.0
        e:
            20xbfeohlln37gdvh5fjqdr5ygkm0xan:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                args:
                    - --model
                    - ft:gpt-4.1-mini-2025-04-14:personal:svc-41mini-sft-dpo-80usd-sft:CLB4qudK
                    - --run-name
                    - SFT 41mini backfill
                    - --tags
                    - svc,41mini,sft,backfill
                codePath: scripts/wandb_sync_openai_ft.py
                codePathLocal: scripts/wandb_sync_openai_ft.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "195604680704"
                email: kordokrip@gmail.com
                executable: /opt/anaconda3/envs/langchain-basics/bin/python
                host: SungHoui-MacBookPro.local
                memory:
                    total: "17179869184"
                os: macOS-15.7.1-arm64-arm-64bit
                program: /Users/sungho-kang/svc-llm-template/scripts/wandb_sync_openai_ft.py
                python: CPython 3.12.11
                root: /Users/sungho-kang/svc-llm-template
                startedAt: "2025-09-30T00:02:35.715Z"
                writerId: 20xbfeohlln37gdvh5fjqdr5ygkm0xan
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 95
                - 105
            "2":
                - 95
                - 105
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.11
            "5": 0.22.0
            "12": 0.22.0
            "13": darwin-arm64
